version: '3.8'
services:
  web-app:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./web-app:/app
    command: npm run dev
    depends_on:
      - server
      - db

  server:
    build: ./server
    ports:
      - '3001:3000'
    volumes:
      - ./server:/app
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
